rn_sdk_root = File.expand_path('../RNSDK', __dir__)

ENV['NODE_PATH'] = "#{rn_sdk_root}/node_modules"

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', rn_sdk_root]).strip

platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false

prepare_react_native_project!

target 'RNSDKWrapper' do
  use_frameworks! :linkage => :static

  use_react_native!(
    :path => "../RNSDK/node_modules/react-native",
    :app_path => rn_sdk_root,
    :hermes_enabled => true,
    :fabric_enabled => false
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      "../RNSDK/node_modules/react-native",
      :mac_catalyst_enabled => false
    )
  end
end